// Generated by scripts/generate-seo-images.ts. Do not edit by hand.
/** Products that have a 1200x630 share image at /og/<slug>.jpg. */
export const PRODUCTS_WITH_SHARE_IMAGE = new Set<string>([
  "iris-gown",
  "ember-circle-kaftan",
  "scarlet-crystal-set",
  "bloom-cape-set",
  "ayo-fringe-set",
  "coral-fringe-poncho-set",
  "tide-stripe-set",
  "adire-patchwork-set",
  "canvas-shirt-set",
  "ruby-fringe-trouser-set",
  "kemi-peplum-set"
]);
